name: clang-format
on: [push, pull_request]
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3  
    - name: Install clang-format
      run: sudo apt install clang-format
    - name: Test clang-format
      run: . tools/formatting/check-all

