name: Code Style
on:
  push:
    paths:
      - '**.[cht]pp'
      - '**.h'
  pull_request:
    paths:
      - '**.[cht]pp'
      - '**.h'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup python
        uses: actions/setup-python@v6
        with:
         python-version: '3.14'
         check-latest: true
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run checks
        run: pre-commit run -a --show-diff-on-failure --color always -v
      - name: Print pre-commit, and clang-format hook versions
        if: always()
        run: |
          echo "Version of pre-commit: " && pre-commit --version
          echo "Version of clang-format pre-commit hook: " && cat ~/.cache/pre-commit/*/.version
