name: Code Style
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - '**.[cht]pp'
      - '**.h'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
         python-version: '3.10'
         check-latest: true
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit clean
          pre-commit install
      - name: Run checks
        run: pre-commit run --all-files --show-diff-on-failure --color always -v
      - name: Print clang-format and hook versions
        if: always()
        run: |
          echo "installed clang-format version: " && clang-format --version
          echo "pre-commit hook versions: " && cat ~/.cache/pre-commit/*/.version
      - name: Git status
        if: always()
        run: git status
      - name: Full diff
        if: always()
        run: git diff