name: unit-tests
on: [push, pull_request]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: carmehp/opendihu:latest
    steps:
      - name: Go to directory
        run: |
          cd /workspace/opendihu
          pwd
          echo "Listing files in the root directory:"
          ls -lah
          python3 dependencies/scons/scons.py BUILD_TYPE=RELEASE no_examples=TRUE

