name: unit-tests-1-rank
on:
  push:
    branches: [ github-actions ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: maierbn/opendihu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: opendihu
      - name: Check directory exists
        working-directory: ./testing/unit_tests
        run: ls
      - name: Run tests
        working-directory: opendihu/testing/unit_tests/build_release
        run: ./1_rank_tests  
  