name: unit-tests-2-rank
on:
  push:
    branches: [ github-actions ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: maierbn/opendihu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: opendihu         
      - name: Check directory exists
        working-directory: opendihu/testing/unit_testing
        run: ls
      - name: Run tests
        working-directory: opendihu/testing/unit_testing/build_release
        run: ./2_rank_tests  
