name: unit-tests
on: [push, pull_request]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: carmehp/opendihu:latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Checkout head
        run: git checkout HEAD^
      - name: Build 
        working-directory: opendihu
        run: python3 dependencies/scons/scons.py BUILD_TYPE=RELEASE no_examples=TRUE

